on:
  push:
  pull_request:
    types: [opened, edited, closed]
  issues:
    types: [opened, edited, closed]
  release:
    types: [released]

permissions: read-all

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on push
        if: github.event_name == 'push'
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            🚀 **Push detected**
            Repository: https://github.com/${{ github.repository }}
            User: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Commits:
            ${{ join(github.event.commits.*.message, '\n- ') }}
          auto-generate-message: false

      - name: Notify PR Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            🆕 **Pull Request Opened**
            Repo: https://github.com/${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.actor }}
          auto-generate-message: false

      # PR Edited
      - name: Notify PR Edited
        if: github.event_name == 'pull_request' && github.event.action == 'edited'
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            ✏️ **Pull Request Edited**
            Repo: https://github.com/${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            Editor: ${{ github.actor }}
          auto-generate-message: false

      # PR Merged
      - name: Notify PR Merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            ✅ **Pull Request Merged**
            Repo: https://github.com/${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            Merged by: ${{ github.actor }}
          auto-generate-message: false

      # PR Closed without Merge
      - name: Notify PR Closed (Not Merged)
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged != true
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            ❌ **Pull Request Closed without Merge**
            Repo: https://github.com/${{ github.repository }}
            Title: ${{ github.event.pull_request.title }}
            Closed by: ${{ github.actor }}
          auto-generate-message: false


      - name: Notify on issue
        if: github.event_name == 'issues'
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            📝 **Issue ${{ github.event.action }}**
            Repository: https://github.com/${{ github.repository }}
            Title: ${{ github.event.issue.title }}
            User: ${{ github.actor }}
          auto-generate-message: false

      - name: Notify on release
        if: github.event_name == 'release'
        uses: issaimaru/traq-webhook@v1.0
        with:
          webhook-id: ${{ secrets.WEBHOOK_ID }}
          message: |
            📦 **New Release Published**
            Repository: https://github.com/${{ github.repository }}
            Release: ${{ github.event.release.name }}
            Published by: ${{ github.actor }}
          auto-generate-message: false
